In [17]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
import datetime
from dateutil.relativedelta import relativedelta
from skinet.utils.athena_tools import *
import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import matplotlib.gridspec as gridspec 
warnings.filterwarnings("ignore")

In [20]:
conn = athena_connection()
df = load_from_athena(conn, '''
SELECT DISTINCT telf2
     , CASE WHEN ctype_l = 'W00' THEN 'HOME'
            WHEN conn_type = 'A01' THEN 'CMS'
            ELSE 'ELSE' END AS prod
     , conn_type, ctype_l, SUBSTR(conn_date, 1, 6) AS ym
     , cstat
  FROM default.monthly_deadline_202011
 WHERE cstat IN ('1', '2')                -- 계약상태 개시 or 중지
''')

...tmp_db name = tmp_20201208_10_41_50_cf0319f19a554ffd2c2a9b9f431b5d4aecabd3bf
Start creating table
drop table if exists default.tmp_20201208_10_41_50_cf0319f19a554ffd2c2a9b9f431b5d4aecabd3bf
<< table not exist

        create  table         default.tmp_20201208_10_41_50_cf0319f19a554ffd2c2a9b9f431b5d4aecabd3bf
        with (format='Parquet', parquet_compression='GZIP')
        as

SELECT DISTINCT telf2
     , CASE WHEN ctype_l = 'W00' THEN 'HOME'
            WHEN conn_type = 'A01' THEN 'CMS'
            ELSE 'ELSE' END AS prod
     , conn_type, ctype_l, SUBSTR(conn_date, 1, 6) AS ym
     , cstat
  FROM default.monthly_deadline_202011
 WHERE cstat IN ('1', '2')                -- 계약상태 개시 or 중지

.
>> Athena Query Success!!
>> Athena Query EXCUTION COMPLETE....
>> S3 FILE GENERATION SUCCESS!! (File count: 9)
Elapsed Time = 13.54
>> Start downloading table
aws s3 cp s3://adt-sandbox/dsc/tables/efc78bae-f747-44b6-a46d-9cf82f826669 /home/skinet/tmp/tmp_20201208_10_41_50_cf0319f19a554ffd2c2a9b9f431b5d4aecabd3bf --recursive
Elapsed Time = 12.63
>> Loading data
Dropping tmp db
<< Delete s3://adt-sandbox/dsc/tables/efc78bae-f747-44b6-a46d-9cf82f826669
Removing tmp_dir!
Elapsed Time for downloading and loading = 6.30
Total Elapsed Time = 32.46

In [25]:
# 이상휴대폰번호 판단 함수 
# 등차수열이거나(ex.01012345678) 다 똑같은 번호거나(ex.01000000000), 위의 이상번호 리스트에 포함되어 있거나.

def valid_number(x):
      nums = list(str(x)) 
      n = len(nums)
      answer=[]
      i = 3
      
      while i <= n-3:
            if int(nums[i]) - int(nums[i+1]) == int(nums[i+1]) - int(nums[i+2]):
                  answer.append(True)
            else:
                  answer.append(False)
            i += 1
      
      if (all(answer) == True):
            return False
      else:
            return True

In [26]:
df.shape

(623456, 7)

In [27]:
# 16. 휴대폰번호 전처리 및 중복 제거

df['telf2'] = df['telf2'].str.replace('\D|\s', '', regex=True)  # 숫자가 아닌 글자랑 공백 날리기
df['telf2'] = np.where(df['telf2'].str[0] != '0', "0"+df['telf2'], df['telf2'])   # 맨 앞에 0이 없으면 0 붙여주기

df['telf_valid_1'] = df['telf2'].str.contains('^01([0|1|6|7|8|9]?)-?([0-9]{3,4})-?([0-9]{4})$', regex=True)  # 자릿수가 맞는지 확인하기
df['telf_valid_2'] = df['telf2'].apply(valid_number)                                                        # 위에 정의한 함수를 통해 valid한지 확인하기
df['telf_valid_final'] = np.where((df['telf_valid_1'] == True) & (df['telf_valid_2'] == True), True, False)
df['telf_valid_final'] = df['telf_valid_final'].map({True : 1, False : 0})                                  # 최종적으로 valid한지 확인

In [34]:
df[(df['telf_valid_final']==1) & (df['prod']!='ELSE')][['telf2', 'prod', 'ym']]

              telf2  prod      ym
0       01036782512   CMS  201803
2       01092334867   CMS  201407
3       01071676520   CMS  201702
4       01065705617   CMS  201909
5       01036295495   CMS  201909
6       01050969002  HOME  202003
7       01054750395  HOME  202008
8       01080280039  HOME  202008
9       01084469594   CMS  201705
13      01054873266   CMS  201310
14      01090784876   CMS  201705
16      01035917436   CMS  201903
20      01093440982   CMS  201903
21      01064222392   CMS  202007
22      01037877896  HOME  201910
23      01035644014   CMS  201910
24      01035356456   CMS  201004
25      01050591229   CMS  201004
27      01063695631   CMS  202004
28      01040423631   CMS  201903
30      01062469589  HOME  202004
32      01024501251   CMS  202009
34      01063824868   CMS  201907
35      01088146539   CMS  202001
36      01077514018   CMS  201611
37      01037125047   CMS  201905
40      01053878853   CMS  201912
41      01088653064   CMS  202011
46      01033325751   CMS  201804
47      01034268780   CMS  201810
...             ...   ...     ...
623415  01054354400   CMS  201803
623419  01037467434   CMS  201502
623420  01053865536   CMS  201402
623421  01049072146   CMS  201205
623422  01086851514   CMS  201807
623423  01093551165   CMS  200611
623424  01093542088   CMS  201901
623425  01075892330   CMS  201912
623426  01065602052   CMS  201805
623427  01025682415   CMS  201804
623428  01077526114   CMS  201805
623430  01094299923   CMS  201412
623431  01085458188   CMS  201412
623432  01099866409   CMS  202006
623433  01096405618   CMS  201108
623434  01022923416   CMS  202009
623435  01032055858  HOME  202009
623436  01072716704   CMS  202011
623437  01044745150   CMS  201705
623438  01031865879   CMS  201906
623439  01074427441   CMS  201906
623440  01040046664   CMS  201512
623441  01023220532   CMS  202002
623442  01089727417   CMS  201806
623444  01048308805   CMS  201604
623445  01073300375   CMS  201704
623450  01026195738   CMS  201804
623451  01051188384  HOME  201911
623452  01074172114   CMS  201505
623454  01031934972   CMS  201910

[440820 rows x 3 columns]

In [36]:
df[(df['telf_valid_final']==1) & (df['prod']!='ELSE')][['telf2', 'prod', 'ym']].to_csv('고객_휴대폰번호_11월마감기준.csv', encoding='utf-8-sig')

In [ ]:
df.telf2.nunique()

In [ ]:
df.shape